#!/bin/bash
LIBTOOLM4="/usr/local/share/libtool/libltdl"

if test -d "$LIBTOOLM4"; then
	echo "+ aclocal ${LIBTOOLM4}"
	aclocal -I ${LIBTOOLM4}
else
	echo "+ aclocal"
	aclocal
fi
set -x
libtoolize --force
autoheader
automake --foreign --add-missing --copy
autoconf
